sudo: required

language: cpp

services:
  - docker

script:
- docker build -f dist/docker/Dockerfile -t hexgearinc/ryzomcore-shard .

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push hexgearinc/ryzomcore-shard
  on:
    branch: docker
